#Align player to camera on left & right clicks (delayed by Flick Timeout)
aimPlayerOnInteract = true
#Angle in degrees within the player will slightly follow camera rotation
#Range: 0 ~ 90
followYaw = 45
#Does camera should rotate freely during elytra flight
freeCameraDuringElytraFlight = false

